### ISSUE TITLE
Pagina di lista dei post

### ISSUE THREAD

**Issue by olistik** [meh-42/blog#5]

**Comment by olistik** [comment]
@EnigmaEdivad Come nel caso della pagina index dei Tag, aggiorna il frammento di conteggio dei post: https://github.com/meh-42/blog/blob/master/app/views/posts/index.html.erb#L2

**Comment by EnigmaEdivad** [comment]
Creo una pull request anche per questo o vado direttamente in master?

**Comment by olistik** [comment]
@EnigmaEdivad vai sano su `master`. 🙂

**Comment by EnigmaEdivad** [comment]
Thanks
